#!/usr/bin/env sh
sed -i '/^.\{5,\}}$/{s/\s\{3,\}{/                                                                                              {/;s/^\(.\{60\}\)\s\+{/\1{/;s/ *}$/ }/}' src/**/*.y
prettier -w --prose-wrap=always **/*.md
ormolu -i **/*.hs
