#!/usr/bin/env sh
sed -i '/^.\{4,\}[^-]}$/{s/\s\{3,\}{/                                                                                              {/;s/^\(.\{60\}\)\s\+{/\1{/;s/ *}$/ }/}' src/**/*.y
prettier -w --prose-wrap=always **/*.md
ormolu -m inplace **/*.hs
