#!/usr/bin/env sh
cat <<HERE | stack run
shuffler shift(index,A, Alen ,B, Blen){
    A[(index + 1) % Alen] ;
    B[(index + Blen - 1) % Blen]
}

shuffler swap(index,A, Alen ,B, Blen){
    B[(index) % Blen] ;
    A[(index) % Alen]
}


shuffler doubler(index,A, Alen){
    A[(index) % Alen] ;
    A[(index) % Alen]
}

mapper haha(i,a,x,y){
    a*x  ; a+y
}

mapper id(i,x,y) {x;y}

@generateSeq (1, 10 )
  | @split(2,1)
  | haha(10)
  | @join(2,1)
  | id()
HERE
exit 0

  | 2:i { haha(i+1) | swap() | id() | shift() | haha(-1) }




@generateSeq (1, 10 )
  | @split(2,1)
  | haha(10)
  | @join(2,1)
  | id()
