#!/usr/bin/env sh
cat <<HERE | stack run
shuffler lol(length,index){ (index + 1) % length}
mapper haha(a,x){x + a}

@generateSeq(50)
  | lol()
  | haha(5)
  | lol()
  | haha(1)
  | lol()
  | haha(2)
  | lol()
  | haha(3)
HERE


