#!/usr/bin/env sh
cat <<HERE | stack run
shuffler lol(length,index){ (index + 1) % length ; index }
mapper haha(a,x){x + a;42}

@generateSeq ( 2, 50 )
  | haha(0)
  | 10:i { haha(i) | lol() | haha(-1) }
  | haha(0)
HERE
