name: gaiwan
version: 0.1.0.0
github: "TOPLLab/gaiwan"
license: MIT
author: "Robbert Gurdeep Singh"
maintainer: "Robbert.GurdeepSingh@UGent.be"
copyright: "2020 Robbert Gurdeep Singh"

extra-source-files:
  - README.md
  - ChangeLog.md
  - src/Language/Gaiwan.y
  - src/Language/Tokens.x

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/gaiwan#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - mtl
  - lens
  - containers
  - OpenCL
  - aeson
  - bytestring
  - text
  - vector

library:
  source-dirs: src

executables:
  gaiwan-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      #- -dynamic
    # Use dynamic for dynamic linking, remove for public
    dependencies:
      - gaiwan
      - bytestring

tests:
  gaiwan-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - gaiwan
      - hspec
      - raw-strings-qq # for serialization tests
      - QuickCheck
